
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import DAO.*;
import Classe.*;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author chris
 */
public class EA_Ajout_Collaborateur extends javax.swing.JPanel {

    /**
     * Creates new form ae_ajout
     */
    public EA_Ajout_Collaborateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexe = new javax.swing.ButtonGroup();
        situation = new javax.swing.ButtonGroup();
        ea_ajout_collaborateur_perso = new javax.swing.JPanel();
        ea_prenom = new javax.swing.JTextField();
        l_prenom = new javax.swing.JLabel();
        ea_nom = new javax.swing.JTextField();
        l_nom = new javax.swing.JLabel();
        ea_femme_RadioButton = new javax.swing.JRadioButton();
        ea_homme_RadioButton = new javax.swing.JRadioButton();
        l_sexe = new javax.swing.JLabel();
        l_rue = new javax.swing.JLabel();
        ea_rue = new javax.swing.JTextField();
        l_cpos = new javax.swing.JLabel();
        l_ville = new javax.swing.JLabel();
        ea_code_postale = new javax.swing.JTextField();
        ea_ville = new javax.swing.JTextField();
        l_sperso = new javax.swing.JLabel();
        ea_marie_RadioButton = new javax.swing.JRadioButton();
        ea_veuf_RadioButton = new javax.swing.JRadioButton();
        ea_celibataire_RadioButton = new javax.swing.JRadioButton();
        l_enfant = new javax.swing.JLabel();
        ea_nbre_enfant_ComboBox = new javax.swing.JComboBox<>();
        l_dnaissance = new javax.swing.JLabel();
        l_vnaissance = new javax.swing.JLabel();
        ea_ville_naissance = new javax.swing.JTextField();
        l_tel = new javax.swing.JLabel();
        ea_telephone = new javax.swing.JTextField();
        ea_mail = new javax.swing.JTextField();
        l_mail = new javax.swing.JLabel();
        ea_date_naissance = new com.toedter.calendar.JDateChooser();
        ea_ajout_collaborateur_pro = new javax.swing.JPanel();
        l_service = new javax.swing.JLabel();
        ea_service_ComboBox = new javax.swing.JComboBox<>();
        l_poste = new javax.swing.JLabel();
        ea_poste = new javax.swing.JTextField();
        l_etude = new javax.swing.JLabel();
        l_specialite = new javax.swing.JLabel();
        ea_specialite = new javax.swing.JTextField();
        ea_niveau_etude = new javax.swing.JTextField();
        l_statut = new javax.swing.JLabel();
        l_datembauche = new javax.swing.JLabel();
        ea_statut_ComboBox = new javax.swing.JComboBox<>();
        ea_date_embauche = new com.toedter.calendar.JDateChooser();
        l_contrat = new javax.swing.JLabel();
        ea_typecontrat = new javax.swing.JComboBox<>();
        l_datefinembauche = new javax.swing.JLabel();
        ea_date_fin_embauche = new com.toedter.calendar.JDateChooser();
        l_cp = new javax.swing.JLabel();
        ea_cp = new javax.swing.JTextField();
        l_rtt = new javax.swing.JLabel();
        ea_rtt = new javax.swing.JTextField();
        l_identifiant = new javax.swing.JLabel();
        l_mdp = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ea_commentaire = new javax.swing.JTextArea();
        jPassword = new javax.swing.JPasswordField();
        ea_identifiant = new javax.swing.JTextField();
        ea_valider = new javax.swing.JButton();

        ea_ajout_collaborateur_perso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Renseignements Personnels", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        ea_ajout_collaborateur_perso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ea_ajout_collaborateur_perso.add(ea_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 28, 170, -1));

        l_prenom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_prenom.setText("Prénom :");
        ea_ajout_collaborateur_perso.add(l_prenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 27, 53, 22));

        ea_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_nomActionPerformed(evt);
            }
        });
        ea_ajout_collaborateur_perso.add(ea_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 28, 170, -1));

        l_nom.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_nom.setText("Nom :");
        ea_ajout_collaborateur_perso.add(l_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 27, 53, 22));

        sexe.add(ea_femme_RadioButton);
        ea_femme_RadioButton.setText("Femme");
        ea_ajout_collaborateur_perso.add(ea_femme_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 27, -1, -1));

        sexe.add(ea_homme_RadioButton);
        ea_homme_RadioButton.setText("Homme");
        ea_ajout_collaborateur_perso.add(ea_homme_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 27, -1, -1));

        l_sexe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_sexe.setText("Sexe :");
        ea_ajout_collaborateur_perso.add(l_sexe, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 35, 22));

        l_rue.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_rue.setText("Rue :");
        ea_ajout_collaborateur_perso.add(l_rue, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 35, 22));
        ea_ajout_collaborateur_perso.add(ea_rue, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 56, 598, -1));

        l_cpos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_cpos.setText("Code postal :");
        ea_ajout_collaborateur_perso.add(l_cpos, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 83, 81, 22));

        l_ville.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_ville.setText("Ville :");
        ea_ajout_collaborateur_perso.add(l_ville, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 83, 39, 22));
        ea_ajout_collaborateur_perso.add(ea_code_postale, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 84, 98, -1));
        ea_ajout_collaborateur_perso.add(ea_ville, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 84, 407, -1));

        l_sperso.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_sperso.setText("Situation personnelle :");
        ea_ajout_collaborateur_perso.add(l_sperso, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 111, 137, 22));

        situation.add(ea_marie_RadioButton);
        ea_marie_RadioButton.setText("Marié");
        ea_ajout_collaborateur_perso.add(ea_marie_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 111, -1, -1));

        situation.add(ea_veuf_RadioButton);
        ea_veuf_RadioButton.setText("Veuf");
        ea_ajout_collaborateur_perso.add(ea_veuf_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 111, -1, -1));

        situation.add(ea_celibataire_RadioButton);
        ea_celibataire_RadioButton.setText("Célibataire");
        ea_ajout_collaborateur_perso.add(ea_celibataire_RadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 111, -1, -1));

        l_enfant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_enfant.setText("Nombre d'enfants à charges :");
        ea_ajout_collaborateur_perso.add(l_enfant, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 111, -1, 22));

        ea_nbre_enfant_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        ea_ajout_collaborateur_perso.add(ea_nbre_enfant_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 112, 147, -1));

        l_dnaissance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_dnaissance.setText("Date de naissance :");
        ea_ajout_collaborateur_perso.add(l_dnaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 139, 118, 22));

        l_vnaissance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_vnaissance.setText("Ville de naissance :");
        ea_ajout_collaborateur_perso.add(l_vnaissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 139, 118, 22));
        ea_ajout_collaborateur_perso.add(ea_ville_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 140, 261, -1));

        l_tel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_tel.setText("Numéro téléphone :");
        ea_ajout_collaborateur_perso.add(l_tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 167, 118, 22));
        ea_ajout_collaborateur_perso.add(ea_telephone, new org.netbeans.lib.awtextra.AbsoluteConstraints(398, 168, 261, -1));
        ea_ajout_collaborateur_perso.add(ea_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 168, 210, -1));

        l_mail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_mail.setText("Email :");
        ea_ajout_collaborateur_perso.add(l_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 167, -1, 22));
        ea_ajout_collaborateur_perso.add(ea_date_naissance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 140, -1));

        ea_ajout_collaborateur_pro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Renseignements Perofessionnels", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        l_service.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_service.setText("Service :");

        ea_service_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner", "RH", "Logistique", "Production", "Qualité", "Informatique", "Direction", "QSE", " " }));

        l_poste.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_poste.setText("Poste :");

        ea_poste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_posteActionPerformed(evt);
            }
        });

        l_etude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_etude.setText("Niveau d'étude :");

        l_specialite.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_specialite.setText("Spécialité :");

        ea_specialite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_specialiteActionPerformed(evt);
            }
        });

        ea_niveau_etude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_niveau_etudeActionPerformed(evt);
            }
        });

        l_statut.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_statut.setText("Statut :");

        l_datembauche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_datembauche.setText("Date d'embauche :");

        ea_statut_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner", "Cadre", "ETAM", "OUVRIER", " " }));

        l_contrat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_contrat.setText("Type de contrat");

        ea_typecontrat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sélectionner", "CDI", "CDD", "Interim", "Stage" }));

        l_datefinembauche.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_datefinembauche.setText("Date fin d'embauche");

        l_cp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_cp.setText("Congés payés :");

        ea_cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_cpActionPerformed(evt);
            }
        });

        l_rtt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_rtt.setText("RTT :");

        ea_rtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_rttActionPerformed(evt);
            }
        });

        l_identifiant.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_identifiant.setText("Identifiant");

        l_mdp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        l_mdp.setText("Mot de passe");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Commentaire :");

        ea_commentaire.setColumns(20);
        ea_commentaire.setRows(5);
        jScrollPane1.setViewportView(ea_commentaire);

        jPassword.setText("jPasswordField1");
        jPassword.setEnabled(false);
        jPassword.setOpaque(false);

        ea_identifiant.setEnabled(false);

        javax.swing.GroupLayout ea_ajout_collaborateur_proLayout = new javax.swing.GroupLayout(ea_ajout_collaborateur_pro);
        ea_ajout_collaborateur_pro.setLayout(ea_ajout_collaborateur_proLayout);
        ea_ajout_collaborateur_proLayout.setHorizontalGroup(
            ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                .addComponent(l_service, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ea_service_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ea_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                .addComponent(l_etude, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(ea_niveau_etude, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(ea_specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                .addComponent(l_statut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(ea_statut_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(l_datembauche)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ea_date_embauche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                            .addComponent(l_contrat)
                            .addGap(18, 18, 18)
                            .addComponent(ea_typecontrat, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(l_datefinembauche)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ea_date_fin_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ea_ajout_collaborateur_proLayout.createSequentialGroup()
                            .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                    .addComponent(l_identifiant)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ea_identifiant))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                    .addComponent(l_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(ea_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                    .addComponent(l_rtt)
                                    .addGap(10, 10, 10)
                                    .addComponent(ea_rtt, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ea_ajout_collaborateur_proLayout.createSequentialGroup()
                                    .addComponent(l_mdp)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap()))
                    .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        ea_ajout_collaborateur_proLayout.setVerticalGroup(
            ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_service, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_poste, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ea_service_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ea_poste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_etude, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_specialite, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ea_niveau_etude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ea_specialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_statut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ea_statut_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_datembauche, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ea_date_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_contrat)
                        .addComponent(ea_typecontrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ea_date_fin_embauche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(l_datefinembauche)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(l_cp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ea_cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(l_rtt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ea_ajout_collaborateur_proLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ea_rtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_identifiant)
                    .addComponent(l_mdp)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ea_identifiant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ea_ajout_collaborateur_proLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        ea_valider.setText("Valider");
        ea_valider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_validerMouseClicked(evt);
            }
        });
        ea_valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ea_ajout_collaborateur_perso, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(ea_valider))
                    .addComponent(ea_ajout_collaborateur_pro, javax.swing.GroupLayout.PREFERRED_SIZE, 670, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ea_ajout_collaborateur_perso, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ea_ajout_collaborateur_pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ea_valider)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ea_posteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_posteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_posteActionPerformed

    private void ea_specialiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_specialiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_specialiteActionPerformed

    private void ea_niveau_etudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_niveau_etudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_niveau_etudeActionPerformed

    private void ea_cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_cpActionPerformed

    private void ea_rttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_rttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_rttActionPerformed

    private void ea_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_nomActionPerformed

    private void ea_validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_validerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ea_validerActionPerformed

    private void ea_validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_validerMouseClicked

     int i = 0;
        
    if ("".equals(ea_nom.getText())){l_nom.setForeground(Color.RED);i++;}else{l_nom.setForeground(Color.BLACK);}
    if ("".equals(ea_prenom.getText())){l_prenom.setForeground(Color.RED);i++;}else{l_prenom.setForeground(Color.BLACK);}
    if ("".equals(ea_rue.getText())){l_rue.setForeground(Color.RED);i++;}else{l_rue.setForeground(Color.BLACK);}
    if ("".equals(ea_code_postale.getText())|| ea_code_postale.getText().matches("[a-zA-Z]*")){l_cpos.setForeground(Color.RED);i++;}else{l_cpos.setForeground(Color.BLACK);}
    if ("".equals(ea_ville.getText())){l_ville.setForeground(Color.RED);i++;}else{l_ville.setForeground(Color.BLACK);}
    if (ea_date_naissance.getDate() == null){l_dnaissance.setForeground(Color.RED);i++;}else{l_dnaissance.setForeground(Color.BLACK);}
    if ("".equals(ea_ville_naissance.getText())){l_vnaissance.setForeground(Color.RED);i++;}else{l_vnaissance.setForeground(Color.BLACK);}
    if ("".equals(ea_mail.getText())){l_mail.setForeground(Color.RED);i++;}else{l_mail.setForeground(Color.BLACK);}
    if ("".equals(ea_telephone.getText())||ea_telephone.getText().matches("[a-zA-Z]*")){l_tel.setForeground(Color.RED);i++;}else{l_tel.setForeground(Color.BLACK);}
    if (ea_nbre_enfant_ComboBox.getSelectedIndex()== 0){l_enfant.setForeground(Color.RED);i++;}else{l_enfant.setForeground(Color.BLACK);}
    
    if (ea_marie_RadioButton.isSelected() == false && ea_veuf_RadioButton.isSelected() == false && ea_celibataire_RadioButton.isSelected() == false)
        {l_sperso.setForeground(Color.RED);i++;}else{l_sperso.setForeground(Color.BLACK);}
    
    if (ea_homme_RadioButton.isSelected() == false && ea_femme_RadioButton.isSelected() == false)
        {l_sexe.setForeground(Color.RED);i++;}else{l_sexe.setForeground(Color.BLACK);}
    
    if (ea_service_ComboBox.getSelectedIndex()== 0){l_service.setForeground(Color.RED);i++;}else{l_service.setForeground(Color.BLACK);}
    if (ea_statut_ComboBox.getSelectedIndex()== 0){l_statut.setForeground(Color.RED);i++;}else{l_statut.setForeground(Color.BLACK);}
    if (ea_typecontrat.getSelectedIndex()== 0){l_contrat.setForeground(Color.RED);i++;}else{l_contrat.setForeground(Color.BLACK);}
    if (ea_date_embauche.getDate() == null){l_datembauche.setForeground(Color.RED);i++;}else{l_datembauche.setForeground(Color.BLACK);}
    if ("".equals(ea_poste.getText())){l_poste.setForeground(Color.RED);i++;}else{l_poste.setForeground(Color.BLACK);}
    if ("".equals(ea_niveau_etude.getText())){l_etude.setForeground(Color.RED);i++;}else{l_etude.setForeground(Color.BLACK);}
    if ("".equals(ea_specialite.getText())){l_specialite.setForeground(Color.RED);i++;}else{l_specialite.setForeground(Color.BLACK);}
    if ("".equals(ea_cp.getText())||ea_cp.getText().matches("[a-zA-Z]*")){l_cp.setForeground(Color.RED);i++;}else{l_cp.setForeground(Color.BLACK);}
    if ("".equals(ea_rtt.getText())||ea_rtt.getText().matches("[a-zA-Z]*")){l_rtt.setForeground(Color.RED);i++;}else{l_rtt.setForeground(Color.BLACK);}
        
    if (ea_typecontrat.getSelectedIndex()!= 1 && ea_date_fin_embauche.getDate() == null){
        l_datefinembauche.setForeground(Color.RED);
        i++;
    }else{l_contrat.setForeground(Color.BLACK);}
    
    if ( i > 0)
    {
      JOptionPane.showMessageDialog(null,"Plusieurs champs obligatoires: Ne sont pas renseignés ou erronés !\n\nVeuillez les modifier.","Informations",JOptionPane.INFORMATION_MESSAGE);
    }
        else
        {
          
          String prenom = ea_prenom.getText();           
          String ea_identifiant = ea_nom.getText() + prenom.substring(0,2);
          String ea_mdp = "0000";
          
            int service = 0;

                if (ea_service_ComboBox.getSelectedItem()=="RH") {
                    service = 1;
                }
                if (ea_service_ComboBox.getSelectedItem()=="Logistique") {
                    service = 2;
                }
                if (ea_service_ComboBox.getSelectedItem()=="Production") {
                    service = 3;
                }
                if (ea_service_ComboBox.getSelectedItem()=="Qualité") {
                    service = 4;
                }
                if (ea_service_ComboBox.getSelectedItem()=="Informatique") {
                    service = 5;
                }
                if (ea_service_ComboBox.getSelectedItem()=="Direction") {
                    service = 6;
                }
                if (ea_service_ComboBox.getSelectedItem()=="QSE") {
                    service = 7;
                }

                String sexe = "";

                if (ea_homme_RadioButton.isSelected()) {
                    sexe="homme";
                }
                    else {
                        sexe="femme";
                    }

                String situation = "";

                if (ea_marie_RadioButton.isSelected()) {
                    sexe="Marié";
                }
                if (ea_veuf_RadioButton.isSelected()) {
                    sexe="Veuf";
                }
                if (ea_celibataire_RadioButton.isSelected()) {
                    sexe="Célibataire";
                }

                int nb_enfant = ea_nbre_enfant_ComboBox.getSelectedIndex();

                String statut = "";
                if (ea_statut_ComboBox.getSelectedIndex()==0) {
                    statut = "Cadre";
                }
                if (ea_statut_ComboBox.getSelectedIndex()==1) {
                    statut = "ETAM";
                }
                if (ea_statut_ComboBox.getSelectedIndex()==2) {
                    statut = "Ouvrier";
                }

                String typecontrat = "";
                if (ea_typecontrat.getSelectedIndex()==0) {
                    typecontrat = "CDI";
                }
                if (ea_typecontrat.getSelectedIndex()==1) {
                    typecontrat = "CDD";
                }
                if (ea_typecontrat.getSelectedIndex()==2) {
                    typecontrat = "Intérim";
                }
                if (ea_typecontrat.getSelectedIndex()==3) {
                    typecontrat = "Stage";
                }

                String date_embauche = "";
                String date_naissance="";
                String date_fin_contrat = "";

                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                date_embauche = sdf.format(ea_date_embauche.getDate());
                java.sql.Date sqlDate_embauche = java.sql.Date.valueOf( date_embauche );

                SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                date_naissance = sdf1.format(ea_date_naissance.getDate());
                java.sql.Date sqlDate_naissance = java.sql.Date.valueOf( date_naissance );

                SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
                java.sql.Date sqlDate_fincontrat = null;

                if (ea_date_fin_embauche.getDate() != null) {
                    date_fin_contrat = sdf2.format(ea_date_fin_embauche.getDate());
                    sqlDate_fincontrat = java.sql.Date.valueOf( date_fin_contrat );
                }

                int code_postale = Integer.parseInt(ea_code_postale.getText());
                int rtt = Integer.parseInt(ea_rtt.getText());
                int cp = Integer.parseInt(ea_cp.getText());

                Personnel P = new Personnel (ea_nom.getText(),ea_prenom.getText(),sexe ,ea_rue.getText(),code_postale,ea_ville.getText(),
                                statut,sqlDate_naissance,ea_ville_naissance.getText(),
                                ea_telephone.getText(),ea_mail.getText(),situation,nb_enfant, sqlDate_embauche,rtt,
                                cp,ea_poste.getText(),ea_niveau_etude.getText(),ea_specialite.getText(),ea_commentaire.getText(),ea_identifiant
                                ,ea_mdp,typecontrat,sqlDate_fincontrat,service);

                PersonnelDAO GRH = new PersonnelDAO();
                GRH.Insert(P);
         
         ea_nom.setText("");
         ea_prenom.setText("");
         ea_homme_RadioButton.setText("");
         ea_femme_RadioButton.setText("");
         ea_rue.setText("");
         ea_code_postale.setText("");
         ea_ville.setText("");
         ea_statut_ComboBox.setSelectedIndex(0);
         ea_date_naissance.setCalendar(null);
         ea_ville_naissance.setText("");
         ea_telephone.setText("");
         ea_mail.setText("");
         ea_marie_RadioButton.setText("");
         ea_veuf_RadioButton.setText("");
         ea_celibataire_RadioButton.setText("");
         ea_nbre_enfant_ComboBox.setSelectedIndex(0);
         ea_date_embauche.setCalendar(null);
         ea_rtt.setText("");
         ea_cp.setText("");
         ea_poste.setText("");
         ea_niveau_etude.setText("");
         ea_specialite.setText("");
         ea_commentaire.setText("");
         ea_identifiant = "";
         ea_typecontrat.setSelectedIndex(0);
         ea_date_fin_embauche.setCalendar(null);
         ea_service_ComboBox.setSelectedIndex(0);      
                
                
        JOptionPane.showMessageDialog(null,"Nouvel ajout réussi !","Informations",JOptionPane.INFORMATION_MESSAGE);     
        }
    }//GEN-LAST:event_ea_validerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ea_ajout_collaborateur_perso;
    private javax.swing.JPanel ea_ajout_collaborateur_pro;
    private javax.swing.JRadioButton ea_celibataire_RadioButton;
    private javax.swing.JTextField ea_code_postale;
    private javax.swing.JTextArea ea_commentaire;
    private javax.swing.JTextField ea_cp;
    private com.toedter.calendar.JDateChooser ea_date_embauche;
    private com.toedter.calendar.JDateChooser ea_date_fin_embauche;
    private com.toedter.calendar.JDateChooser ea_date_naissance;
    private javax.swing.JRadioButton ea_femme_RadioButton;
    private javax.swing.JRadioButton ea_homme_RadioButton;
    private javax.swing.JTextField ea_identifiant;
    private javax.swing.JTextField ea_mail;
    private javax.swing.JRadioButton ea_marie_RadioButton;
    private javax.swing.JComboBox<String> ea_nbre_enfant_ComboBox;
    private javax.swing.JTextField ea_niveau_etude;
    private javax.swing.JTextField ea_nom;
    private javax.swing.JTextField ea_poste;
    private javax.swing.JTextField ea_prenom;
    private javax.swing.JTextField ea_rtt;
    private javax.swing.JTextField ea_rue;
    private javax.swing.JComboBox<String> ea_service_ComboBox;
    private javax.swing.JTextField ea_specialite;
    private javax.swing.JComboBox<String> ea_statut_ComboBox;
    private javax.swing.JTextField ea_telephone;
    private javax.swing.JComboBox<String> ea_typecontrat;
    private javax.swing.JButton ea_valider;
    private javax.swing.JRadioButton ea_veuf_RadioButton;
    private javax.swing.JTextField ea_ville;
    private javax.swing.JTextField ea_ville_naissance;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_contrat;
    private javax.swing.JLabel l_cp;
    private javax.swing.JLabel l_cpos;
    private javax.swing.JLabel l_datefinembauche;
    private javax.swing.JLabel l_datembauche;
    private javax.swing.JLabel l_dnaissance;
    private javax.swing.JLabel l_enfant;
    private javax.swing.JLabel l_etude;
    private javax.swing.JLabel l_identifiant;
    private javax.swing.JLabel l_mail;
    private javax.swing.JLabel l_mdp;
    private javax.swing.JLabel l_nom;
    private javax.swing.JLabel l_poste;
    private javax.swing.JLabel l_prenom;
    private javax.swing.JLabel l_rtt;
    private javax.swing.JLabel l_rue;
    private javax.swing.JLabel l_service;
    private javax.swing.JLabel l_sexe;
    private javax.swing.JLabel l_specialite;
    private javax.swing.JLabel l_sperso;
    private javax.swing.JLabel l_statut;
    private javax.swing.JLabel l_tel;
    private javax.swing.JLabel l_ville;
    private javax.swing.JLabel l_vnaissance;
    private javax.swing.ButtonGroup sexe;
    private javax.swing.ButtonGroup situation;
    // End of variables declaration//GEN-END:variables


}
