
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author afpa
 */
public class EA_Grille_Salaire extends javax.swing.JPanel {

    /**
     * Creates new form EA_Grille_Salaire
     */
    public EA_Grille_Salaire() {
        initComponents();
                
        ea_ouv_formulaire.setVisible(false);
        ea_etam_formulaire.setVisible(false);
        ea_cadre_formulaire.setVisible(false);
        
    }
    
    private void ChargeListe1() {
//        DefaultTableModel dtm = new DefaultTableModel();
//        DAO.PersonnelDAO tab = new  DAO.PersonnelDAO();
//        
//        dtm.addColumn("id");
//        dtm.addColumn("Nom");
//        dtm.addColumn("Prenom");
//        dtm.addColumn("Poste");
//        
//               
//        for(Classe.Personnel p: tab.List_By_nom_centre_cout(nom)){
//        String [] ligne = {Integer.toString(p.getId()),p.getNom(),p.getPrenom(),p.getPoste()};
//        dtm.addRow(ligne);
//        }
//        
//        ea_liste_table.setModel(dtm);
//        ea_liste_table.getColumnModel().getColumn(0).setMinWidth(0);
//        ea_liste_table.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        ea_ouv_ajout = new javax.swing.JButton();
        ea_ouv_sup = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ea_ouv_liste = new javax.swing.JTable();
        ea_ouv_formulaire = new javax.swing.JPanel();
        ea_ouv_coeff = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        ea_ouv_salmini = new javax.swing.JTextField();
        ea_ouv_salmax = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        ea_ouv_modif = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        ea_etam_ajout = new javax.swing.JButton();
        ea_etam_sup = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ea_etam_liste = new javax.swing.JTable();
        ea_etam_formulaire = new javax.swing.JPanel();
        ea_etam_coeff = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        ea_etam_salmini = new javax.swing.JTextField();
        ea_etam_salmax = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        ea_etam_modif = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        ea_cadre_ajout = new javax.swing.JButton();
        ea_cadre_sup = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ea_ouv_liste1 = new javax.swing.JTable();
        ea_cadre_formulaire = new javax.swing.JPanel();
        ea_cadre_coeff = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        ea_cadre_salmini = new javax.swing.JTextField();
        ea_cadre_salmax = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ea_cadre_modif = new javax.swing.JButton();

        jButton9.setText("Modifier");

        jButton10.setText("Supprimer");

        setMaximumSize(new java.awt.Dimension(20000, 20000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(915, 575));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ouvrier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel15.setPreferredSize(new java.awt.Dimension(828, 220));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ea_ouv_ajout.setText("Ajouter");
        ea_ouv_ajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_ouv_ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_ouv_ajoutMouseClicked(evt);
            }
        });
        jPanel15.add(ea_ouv_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 80, -1));

        ea_ouv_sup.setText("Supprimer");
        ea_ouv_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_ouv_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_ouv_supMouseClicked(evt);
            }
        });
        jPanel15.add(ea_ouv_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        ea_ouv_liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Coefficient", "Salaire Mini", "Salaire Max"
            }
        ));
        jScrollPane1.setViewportView(ea_ouv_liste);

        jPanel15.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 170));

        ea_ouv_formulaire.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        ea_ouv_formulaire.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ea_ouv_formulaire.add(ea_ouv_coeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 28, 170, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Salaire max :");
        ea_ouv_formulaire.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 78, -1, 22));
        ea_ouv_formulaire.add(ea_ouv_salmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 127, 170, -1));
        ea_ouv_formulaire.add(ea_ouv_salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 79, 170, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Coefficient :");
        ea_ouv_formulaire.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, 22));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Salaire mini :");
        ea_ouv_formulaire.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 126, -1, 22));

        jPanel15.add(ea_ouv_formulaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 310, 180));

        ea_ouv_modif.setText("Modifier");
        ea_ouv_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_ouv_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_ouv_modifMouseClicked(evt);
            }
        });
        jPanel15.add(ea_ouv_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 80, -1));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ETAM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel14.setPreferredSize(new java.awt.Dimension(828, 220));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ea_etam_ajout.setText("Ajouter");
        ea_etam_ajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_etam_ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_etam_ajoutMouseClicked(evt);
            }
        });
        jPanel14.add(ea_etam_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 80, -1));

        ea_etam_sup.setText("Supprimer");
        ea_etam_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_etam_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_etam_supMouseClicked(evt);
            }
        });
        jPanel14.add(ea_etam_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        ea_etam_liste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Coefficient", "Salaire Mini", "Salaire Max"
            }
        ));
        jScrollPane2.setViewportView(ea_etam_liste);

        jPanel14.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 170));

        ea_etam_formulaire.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        ea_etam_formulaire.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ea_etam_formulaire.add(ea_etam_coeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 28, 170, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel47.setText("Salaire max :");
        ea_etam_formulaire.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 78, -1, 22));
        ea_etam_formulaire.add(ea_etam_salmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 127, 170, -1));
        ea_etam_formulaire.add(ea_etam_salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 79, 170, -1));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel34.setText("Coefficient :");
        ea_etam_formulaire.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, 22));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel35.setText("Salaire mini :");
        ea_etam_formulaire.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 126, -1, 22));

        jPanel14.add(ea_etam_formulaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 310, 180));

        ea_etam_modif.setText("Modifier");
        ea_etam_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_etam_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_etam_modifMouseClicked(evt);
            }
        });
        jPanel14.add(ea_etam_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 80, -1));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(828, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ea_cadre_ajout.setText("Ajouter");
        ea_cadre_ajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_cadre_ajout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_cadre_ajoutMouseClicked(evt);
            }
        });
        jPanel1.add(ea_cadre_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 80, -1));

        ea_cadre_sup.setText("Supprimer");
        ea_cadre_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_cadre_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_cadre_supMouseClicked(evt);
            }
        });
        jPanel1.add(ea_cadre_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        ea_ouv_liste1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Coefficient", "Salaire Mini", "Salaire Max"
            }
        ));
        jScrollPane3.setViewportView(ea_ouv_liste1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 170));

        ea_cadre_formulaire.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        ea_cadre_formulaire.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ea_cadre_formulaire.add(ea_cadre_coeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 28, 170, -1));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Salaire max :");
        ea_cadre_formulaire.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 78, -1, 22));
        ea_cadre_formulaire.add(ea_cadre_salmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 127, 170, -1));
        ea_cadre_formulaire.add(ea_cadre_salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 79, 170, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Coefficient :");
        ea_cadre_formulaire.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, 22));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Salaire mini :");
        ea_cadre_formulaire.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 126, -1, 22));

        jPanel1.add(ea_cadre_formulaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 310, 180));

        ea_cadre_modif.setText("Modifier");
        ea_cadre_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ea_cadre_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_cadre_modifMouseClicked(evt);
            }
        });
        jPanel1.add(ea_cadre_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 80, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 463, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 766));
    }// </editor-fold>//GEN-END:initComponents

    private void ea_ouv_ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_ouv_ajoutMouseClicked
        ea_ouv_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_ouv_ajoutMouseClicked

    private void ea_ouv_modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_ouv_modifMouseClicked
        ea_ouv_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_ouv_modifMouseClicked

    private void ea_ouv_supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_ouv_supMouseClicked
        ea_ouv_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_ouv_supMouseClicked

    private void ea_etam_ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_etam_ajoutMouseClicked
        ea_etam_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_etam_ajoutMouseClicked

    private void ea_etam_modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_etam_modifMouseClicked
        ea_etam_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_etam_modifMouseClicked

    private void ea_etam_supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_etam_supMouseClicked
        ea_etam_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_etam_supMouseClicked

    private void ea_cadre_ajoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_cadre_ajoutMouseClicked
       ea_cadre_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_cadre_ajoutMouseClicked

    private void ea_cadre_modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_cadre_modifMouseClicked
        ea_cadre_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_cadre_modifMouseClicked

    private void ea_cadre_supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_cadre_supMouseClicked
        ea_cadre_formulaire.setVisible(true);
    }//GEN-LAST:event_ea_cadre_supMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ea_cadre_ajout;
    private javax.swing.JTextField ea_cadre_coeff;
    private javax.swing.JPanel ea_cadre_formulaire;
    private javax.swing.JButton ea_cadre_modif;
    private javax.swing.JTextField ea_cadre_salmax;
    private javax.swing.JTextField ea_cadre_salmini;
    private javax.swing.JButton ea_cadre_sup;
    private javax.swing.JButton ea_etam_ajout;
    private javax.swing.JTextField ea_etam_coeff;
    private javax.swing.JPanel ea_etam_formulaire;
    private javax.swing.JTable ea_etam_liste;
    private javax.swing.JButton ea_etam_modif;
    private javax.swing.JTextField ea_etam_salmax;
    private javax.swing.JTextField ea_etam_salmini;
    private javax.swing.JButton ea_etam_sup;
    private javax.swing.JButton ea_ouv_ajout;
    private javax.swing.JTextField ea_ouv_coeff;
    private javax.swing.JPanel ea_ouv_formulaire;
    private javax.swing.JTable ea_ouv_liste;
    private javax.swing.JTable ea_ouv_liste1;
    private javax.swing.JButton ea_ouv_modif;
    private javax.swing.JTextField ea_ouv_salmax;
    private javax.swing.JTextField ea_ouv_salmini;
    private javax.swing.JButton ea_ouv_sup;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
