
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author afpa
 */
public class EA_Grille_Salaire1 extends javax.swing.JPanel {

    /**
     * Creates new form EA_Grille_Salaire
     */
    public EA_Grille_Salaire1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        ea_etam_salmini = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        ea_etam_coeff = new javax.swing.JTextField();
        ea_etam_salmax = new javax.swing.JTextField();
        ea_etam_checkbox = new javax.swing.JCheckBox();
        ea_etam_ajout = new javax.swing.JButton();
        ea_etam_modif = new javax.swing.JButton();
        ea_etam_sup = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        ea_ouv_salmini = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        ea_ouv_salmax = new javax.swing.JTextField();
        ea_ouv_checkbox = new javax.swing.JCheckBox();
        ea_ouv_modif = new javax.swing.JButton();
        ea_ouv_sup = new javax.swing.JButton();
        ea_ouv_ajout = new javax.swing.JButton();
        ea_ouv_coeff1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        ea_cadre_coeff = new javax.swing.JTextField();
        ea_cadre_salmax = new javax.swing.JTextField();
        ea_cadre_salmini = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        ea_cadre_checkbox = new javax.swing.JCheckBox();
        ea_cadre_ajout = new javax.swing.JButton();
        ea_cadre_modif = new javax.swing.JButton();
        ea_cadre_sup = new javax.swing.JButton();

        jButton9.setText("Modifier");

        jButton10.setText("Supprimer");

        setMaximumSize(new java.awt.Dimension(20000, 20000));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setName(""); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(915, 575));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ETAM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel14.setPreferredSize(new java.awt.Dimension(828, 220));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Salaire mini :");
        jPanel14.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 27, -1, 22));
        jPanel14.add(ea_etam_salmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 28, 170, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Coefficient :");
        jPanel14.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, 22));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel45.setText("Salaire max :");
        jPanel14.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 27, -1, 22));
        jPanel14.add(ea_etam_coeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 28, 170, -1));
        jPanel14.add(ea_etam_salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 28, 170, -1));

        ea_etam_checkbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(ea_etam_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 27, -1, -1));

        ea_etam_ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image plus.png"))); // NOI18N
        ea_etam_ajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(ea_etam_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 21, 23));

        ea_etam_modif.setText("Modifier");
        ea_etam_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(ea_etam_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 190, -1, -1));

        ea_etam_sup.setText("Supprimer");
        ea_etam_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel14.add(ea_etam_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 190, -1, -1));

        jPanel4.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, -1));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ouvrier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel15.setPreferredSize(new java.awt.Dimension(828, 220));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel15.add(ea_ouv_salmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 28, 170, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Salaire mini :");
        jPanel15.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 27, -1, 22));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Coefficient :");
        jPanel15.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, 22));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel44.setText("Salaire max :");
        jPanel15.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 27, -1, 22));
        jPanel15.add(ea_ouv_salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 28, 170, -1));

        ea_ouv_checkbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(ea_ouv_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 28, -1, -1));

        ea_ouv_modif.setText("Modifier");
        ea_ouv_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(ea_ouv_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 190, -1, -1));

        ea_ouv_sup.setText("Supprimer");
        ea_ouv_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(ea_ouv_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 190, -1, -1));

        ea_ouv_ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image plus.png"))); // NOI18N
        ea_ouv_ajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel15.add(ea_ouv_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 55, 21, 23));
        jPanel15.add(ea_ouv_coeff1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 28, 170, -1));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(828, 220));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(ea_cadre_coeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 17, 170, -1));
        jPanel1.add(ea_cadre_salmax, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 17, 170, -1));
        jPanel1.add(ea_cadre_salmini, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 17, 170, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel33.setText("Salaire mini :");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 16, -1, 22));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("Salaire max :");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 16, -1, 22));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel32.setText("Coefficient :");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, 22));

        ea_cadre_checkbox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ea_cadre_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(796, 16, -1, -1));

        ea_cadre_ajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image plus.png"))); // NOI18N
        ea_cadre_ajout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ea_cadre_ajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 44, 21, 23));

        ea_cadre_modif.setText("Modifier");
        ea_cadre_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ea_cadre_modif, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 190, -1, -1));

        ea_cadre_sup.setText("Supprimer");
        ea_cadre_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(ea_cadre_sup, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 190, -1, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 463, -1, -1));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 766));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ea_cadre_ajout;
    private javax.swing.JCheckBox ea_cadre_checkbox;
    private javax.swing.JTextField ea_cadre_coeff;
    private javax.swing.JButton ea_cadre_modif;
    private javax.swing.JTextField ea_cadre_salmax;
    private javax.swing.JTextField ea_cadre_salmini;
    private javax.swing.JButton ea_cadre_sup;
    private javax.swing.JButton ea_etam_ajout;
    private javax.swing.JCheckBox ea_etam_checkbox;
    private javax.swing.JTextField ea_etam_coeff;
    private javax.swing.JButton ea_etam_modif;
    private javax.swing.JTextField ea_etam_salmax;
    private javax.swing.JTextField ea_etam_salmini;
    private javax.swing.JButton ea_etam_sup;
    private javax.swing.JButton ea_ouv_ajout;
    private javax.swing.JCheckBox ea_ouv_checkbox;
    private javax.swing.JTextField ea_ouv_coeff1;
    private javax.swing.JButton ea_ouv_modif;
    private javax.swing.JTextField ea_ouv_salmax;
    private javax.swing.JTextField ea_ouv_salmini;
    private javax.swing.JButton ea_ouv_sup;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
