
import DAO.*;
import Principale.*;
import Classe.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author afpa
 */
public class EA_Liste extends javax.swing.JPanel {

    /**
     * Creates new form EA_Liste
     */
    public EA_Liste() {
        initComponents();                                     

       CentreCoutDAO repo = new CentreCoutDAO();
       ea_liste_service.addItem("Selectionnez");
        for (CentreCout c : repo.list()) {
            ea_liste_service.addItem(c.getService());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ea_liste_table = new javax.swing.JTable();
        ea_liste_valider = new javax.swing.JButton();
        ea_liste_service = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Service");

        ea_liste_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prénom", "Poste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ea_liste_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_liste_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ea_liste_table);
        if (ea_liste_table.getColumnModel().getColumnCount() > 0) {
            ea_liste_table.getColumnModel().getColumn(0).setResizable(false);
            ea_liste_table.getColumnModel().getColumn(1).setResizable(false);
            ea_liste_table.getColumnModel().getColumn(2).setResizable(false);
        }

        ea_liste_valider.setText("Valider");
        ea_liste_valider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ea_liste_validerMouseClicked(evt);
            }
        });

        ea_liste_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ea_liste_serviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ea_liste_service, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 258, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(ea_liste_valider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ea_liste_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ea_liste_valider)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ea_liste_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ea_liste_serviceActionPerformed
        DefaultTableModel dtm = new DefaultTableModel();
        DAO.PersonnelDAO tab = new  DAO.PersonnelDAO();
        
        dtm.addColumn("id");
        dtm.addColumn("Nom");
        dtm.addColumn("Prenom");
        dtm.addColumn("Poste");
        
        String nom = ea_liste_service.getSelectedItem().toString();
        
        for(Classe.Personnel p: tab.List_By_nom_centre_cout(nom)){
        String [] ligne = {Integer.toString(p.getId()),p.getNom(),p.getPrenom(),p.getPoste()};
        dtm.addRow(ligne);
        }
        
        ea_liste_table.setModel(dtm);
        ea_liste_table.getColumnModel().getColumn(0).setMinWidth(0);
        ea_liste_table.getColumnModel().getColumn(0).setMaxWidth(0);
    }//GEN-LAST:event_ea_liste_serviceActionPerformed

    private void ea_liste_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_liste_tableMouseClicked
        int i = ea_liste_table.getSelectedRow();
        System.out.println(i);
        String id = ea_liste_table.getModel().getValueAt(i, 0).toString();
        System.out.println(id);
    }//GEN-LAST:event_ea_liste_tableMouseClicked

    private void ea_liste_validerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ea_liste_validerMouseClicked
        Structure main = (Structure)SwingUtilities.getWindowAncestor(this);
        
        // prendre l'id du collaboratuer selectionné
        int i = ea_liste_table.getSelectedRow();
        System.out.println(i);
        String id = ea_liste_table.getModel().getValueAt(i, 0).toString();
        System.out.println(id);
        
        main.Affiche_Formulaire_Modif(id);
        
    }//GEN-LAST:event_ea_liste_validerMouseClicked
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ea_liste_service;
    private javax.swing.JTable ea_liste_table;
    private javax.swing.JButton ea_liste_valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}