
import Classe.Absence;
import DAO.AbsenceDAO;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author chris
 */
public class EC_Congés extends javax.swing.JPanel {

    /**
     * Creates new form EC_Congés
     */
    public EC_Congés() {
        initComponents();
        
        DefaultTableModel dtm = new DefaultTableModel();
        DAO.AbsenceDAO tab = new  DAO.AbsenceDAO();
        
        dtm.addColumn("id");
        dtm.addColumn("Date demande");
        dtm.addColumn("Nom");
        dtm.addColumn("Date début");
        dtm.addColumn("Date fin");
        dtm.addColumn("Type");
        
        for(Classe.Absence p: tab.list()){
        String [] ligne = {Integer.toString(p.getId()),String.valueOf(p.getDate_pose()),p.getNom(),String.valueOf(p.getDate_debut()),String.valueOf(p.getDate_fin()),p.getType()};
        dtm.addRow(ligne);
        
        ec_tableau_conges.setModel(dtm);
        ec_tableau_conges.getColumnModel().getColumn(0).setMinWidth(0);
        ec_tableau_conges.getColumnModel().getColumn(0).setMaxWidth(0);
        
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ec_conges = new javax.swing.JPanel();
        ec_demande_conges = new javax.swing.JButton();
        ec_liste_conges = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ec_tableau_conges = new javax.swing.JTable();
        ec_conges_sup = new javax.swing.JButton();
        ec_conges_modif = new javax.swing.JButton();

        ec_conges.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Congés", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        ec_demande_conges.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ec_demande_conges.setText("Demande de congés");
        ec_demande_conges.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ec_demande_conges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ec_demande_congesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ec_congesLayout = new javax.swing.GroupLayout(ec_conges);
        ec_conges.setLayout(ec_congesLayout);
        ec_congesLayout.setHorizontalGroup(
            ec_congesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ec_congesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ec_demande_conges, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ec_congesLayout.setVerticalGroup(
            ec_congesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ec_congesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ec_demande_conges)
                .addContainerGap())
        );

        ec_liste_conges.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des congés", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 153))); // NOI18N

        ec_tableau_conges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date demande", "Nom", "Date début", "Date fin", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ec_tableau_conges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ec_tableau_congesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ec_tableau_conges);

        javax.swing.GroupLayout ec_liste_congesLayout = new javax.swing.GroupLayout(ec_liste_conges);
        ec_liste_conges.setLayout(ec_liste_congesLayout);
        ec_liste_congesLayout.setHorizontalGroup(
            ec_liste_congesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
            .addGroup(ec_liste_congesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ec_liste_congesLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        ec_liste_congesLayout.setVerticalGroup(
            ec_liste_congesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
            .addGroup(ec_liste_congesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ec_liste_congesLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        ec_conges_sup.setText("Supprimer");
        ec_conges_sup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ec_conges_sup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ec_conges_supMouseClicked(evt);
            }
        });

        ec_conges_modif.setText("Modifier");
        ec_conges_modif.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ec_conges_modif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ec_conges_modifMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ec_liste_conges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ec_conges, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ec_conges_modif)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ec_conges_sup)
                .addGap(378, 378, 378))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ec_conges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ec_liste_conges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ec_conges_sup)
                    .addComponent(ec_conges_modif))
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ec_demande_congesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ec_demande_congesMouseClicked
        // TODO add your handling code here:
        Structure main = (Structure)SwingUtilities.getWindowAncestor(this);
        
        main.Afficher_Demande_Conges();
    }//GEN-LAST:event_ec_demande_congesMouseClicked

    private void ec_tableau_congesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ec_tableau_congesMouseClicked
        int i = ec_tableau_conges.getSelectedRow();
        System.out.println(i);
        String id = ec_tableau_conges.getModel().getValueAt(i, 0).toString();
        System.out.println(id);
    }//GEN-LAST:event_ec_tableau_congesMouseClicked

    private void ec_conges_supMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ec_conges_supMouseClicked
        // TODO add your handling code here:
        int i = ec_tableau_conges.getSelectedRow();
        System.out.println(i);
        String id = ec_tableau_conges.getModel().getValueAt(i, 0).toString();
        System.out.println(id);
        
        Absence a = new Absence();  
       
        a.setId(Integer.parseInt(id));
        
        AbsenceDAO repo = new AbsenceDAO();
        
        int z = JOptionPane.showConfirmDialog(null, "Etes vous sur de vouloir supprimer ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if(z == 0){
        repo.delete(a);
        
        Structure main = (Structure)SwingUtilities.getWindowAncestor(this);
        
        main.Afficher_Conges();
        }
        else
        {
        Structure main = (Structure)SwingUtilities.getWindowAncestor(this);
        
        main.Afficher_Conges();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_ec_conges_supMouseClicked

    private void ec_conges_modifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ec_conges_modifMouseClicked
        // TODO add your handling code here:
        Structure main = (Structure)SwingUtilities.getWindowAncestor(this);
        
        int i = ec_tableau_conges.getSelectedRow();
        System.out.println(i);
        String id = ec_tableau_conges.getModel().getValueAt(i, 0).toString();
        System.out.println(id);
        
        main.Affiche_Modification_conges(id);
    }//GEN-LAST:event_ec_conges_modifMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ec_conges;
    private javax.swing.JButton ec_conges_modif;
    private javax.swing.JButton ec_conges_sup;
    private javax.swing.JButton ec_demande_conges;
    private javax.swing.JPanel ec_liste_conges;
    private javax.swing.JTable ec_tableau_conges;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
