/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author afpa
 */
public class EM_Gestion extends javax.swing.JPanel {

    /**
     * Creates new form EM_Gestion
     */
    public EM_Gestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        em_gestion_collab = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        em_gestion_dateembauche = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        em_gestion_datefin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        em_gestion_poste = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        em_gestion_salaire = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        em_gestion_typecontrat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        em_gestion_renouvelcheckbox = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        em_gestion_changementcheckbox = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        em_gestion_duree = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        em_gestion_augmentation = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        em_gestion_prime = new javax.swing.JTextField();
        em_gestion_valider = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Collaborateur");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 21, -1, -1));

        em_gestion_collab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(em_gestion_collab, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 18, 200, -1));

        jLabel2.setText("Date d'embauche");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 47, -1, -1));
        add(em_gestion_dateembauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 44, 200, -1));

        jLabel3.setText("Date fin de contrat");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 76, -1, -1));
        add(em_gestion_datefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 70, 201, -1));

        jLabel4.setText("Poste");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 99, -1, -1));
        add(em_gestion_poste, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 96, 201, -1));

        jLabel5.setText("Salaire");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 125, -1, -1));
        add(em_gestion_salaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 122, 201, -1));

        jLabel6.setText("Type de contrat");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 151, -1, -1));

        em_gestion_typecontrat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CDI", "CDD", "Interimaire", "Stagiaire" }));
        add(em_gestion_typecontrat, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 148, 201, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Demande");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 195, -1, -1));

        jLabel8.setText("Renouvellement CDD");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 230, -1, -1));
        add(em_gestion_renouvelcheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 230, -1, 14));

        jLabel9.setText("Changement de contrat");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        add(em_gestion_changementcheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 230, -1, 14));

        jLabel10.setText("Durée");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 258, -1, -1));
        add(em_gestion_duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 255, 89, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Rémuneration");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 293, -1, -1));

        jLabel12.setText("Augmentation %");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 324, -1, -1));
        add(em_gestion_augmentation, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 321, 86, -1));

        jLabel13.setText("Prime annuelle");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 350, -1, -1));
        add(em_gestion_prime, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 347, 86, -1));

        em_gestion_valider.setText("Valider");
        add(em_gestion_valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField em_gestion_augmentation;
    private javax.swing.JCheckBox em_gestion_changementcheckbox;
    private javax.swing.JComboBox<String> em_gestion_collab;
    private javax.swing.JTextField em_gestion_dateembauche;
    private javax.swing.JTextField em_gestion_datefin;
    private javax.swing.JTextField em_gestion_duree;
    private javax.swing.JTextField em_gestion_poste;
    private javax.swing.JTextField em_gestion_prime;
    private javax.swing.JCheckBox em_gestion_renouvelcheckbox;
    private javax.swing.JTextField em_gestion_salaire;
    private javax.swing.JComboBox<String> em_gestion_typecontrat;
    private javax.swing.JButton em_gestion_valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
