
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author afpa
 */
public class EM_Validation_congés extends javax.swing.JPanel {

    /**
     * Creates new form EM_Validation_congés
     */
    public EM_Validation_congés() {
        initComponents();
        
//        DefaultTableModel dtm = new DefaultTableModel();
//        DAO.AbsenceDAO tab = new  DAO.AbsenceDAO();
//        
//        dtm.addColumn("id");
//        dtm.addColumn("Date demande");
//        dtm.addColumn("Nom");
//        dtm.addColumn("Date début");
//        dtm.addColumn("Date fin");
//        dtm.addColumn("Type");
//        
//        for(Classe.Absence p: tab.list_by_centre_cout(id_local)){
//        String [] ligne = {Integer.toString(p.getId()),String.valueOf(p.getDate_pose()),p.getNom(),String.valueOf(p.getDate_debut()),String.valueOf(p.getDate_fin()),p.getType()};
//        dtm.addRow(ligne);
//        
//        jTable1.setModel(dtm);
//        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
//        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
//    }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        em_vc_valider = new javax.swing.JButton();
        em_vc_refusee = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Date demande", "Nom", "Date début", "Date fin", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Légende: Jaune = en attente de validation, rouge = demande refusée, vert = demande acceptée ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        em_vc_valider.setText("Valider");
        em_vc_valider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(em_vc_valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        em_vc_refusee.setText("Refusée");
        em_vc_refusee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(em_vc_refusee, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton em_vc_refusee;
    private javax.swing.JButton em_vc_valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
